export interface YouTubeVideoItem {
  title: string;
  id: string;
}

export const YOUTUBE_VIDEOS_LIST: YouTubeVideoItem[] = [
  { title: "Come fermare il tower rush dei Mongoli con i Byz! ☦️​​ ► Age of Empires IV ◄ Gameplay ITA", id: "1D6nTyv7PUI" },
  { title: "Lo stato delle cose sulle community italiane di AoE IV + LANCIO SITO!", id: "rSv9INhUve4" },
  { title: "Macedoni OP su acqua? Stream POV ⛵​​ ► Age of Empires IV ◄ Gameplay ITA", id: "jdaxdcnv7W8" },
  { title: "Build per FAST CASTLE con SENGOKU DAIMYO 🏯​​ ► Age of Empires IV ◄ Gameplay ITA", id: "H92Vl2QUiJs" },
  { title: "Stream POV: Ippodromo inarrestabile e villi che torciano cose 🧯 ► Age of Empires IV ◄ Gameplay ITA", id: "p5DkJ1n4DHI" },
  { title: "Build per l'IPPODROMO con i MACEDONI 🐎 ► Age of Empires IV ◄ Gameplay ITA", id: "Zhoru1aK8Iw" },
  { title: "Come si gioca l'ORDA D'ORO: guida a un all in totale! ⚔️ ► Age of Empires IV ◄ Gameplay ITA", id: "Skfh1-iTtfg" },
  { title: "Giocare MONGOLI come un conqueror: team games 🐎 ► Age of Empires IV ◄ Gameplay ITA", id: "x66WfzK3d2s" },
  { title: "Giocare DELHI come un conqueror: parte 1 🐘 ► Age of Empires IV ◄ Gameplay ITA", id: "OwTuGgYt9CM" },
  { title: "Finale EGC (upper bracket): LucifroN7 vs MarineLorD ⚔ ► Age of Empires IV ◄ Gameplay ITA", id: "bmHZc7agrU0" },
  { title: "4v4 FOLLE su Hedgemaze ► Age of Empires IV ◄ Gameplay ITA", id: "X1OP7uQeDgM" },
  { title: "Inglesi: 2 TC + White Tower: la loro build migliore ♜ ► Age of Empires IV ◄ Gameplay ITA", id: "tB98m5TWOfU" },
  { title: "Ho smatacchiato Eismen. L'avrà presa bene? 🤔 ► Age of Empires IV ◄ Gameplay ITA", id: "BlUjHRlpSFU" },
  { title: "Siamo sicuri di sapere quali siano i cav più forti del gioco? 🐎 ► Age of Empires IV ◄ Gameplay ITA", id: "fB_hD7y35Mo" },
  { title: "Come giocare i TEMPLARI su fiume roccioso 🛡️ ► Age of Empires IV ◄ Gameplay ITA", id: "0Ld_Kum3sh0" },
  { title: "Giovannona prova a fermare il boom di cisterne dei byz! 🦸‍♀️ ► Age of Empires IV ◄ Gameplay ITA", id: "R6duDrI-rxI" },
  { title: "Guida ai tornei di AoE IV e alla scena competitiva 🔥 ► Age of Empires IV ◄", id: "L6nEurV21SM" },
  { title: "Vortix vs LoueMT: ma cosa combinano? ❓❗ ► Age of Empires IV ◄ Gameplay ITA", id: "fyHjmbag8ao" },
  { title: "Longbow + catafratti: la comp inarrestabile dei bizantini ❗ ► Age of Empires IV ◄ Gameplay ITA", id: "Ra8hy4Fw-Uo" },
  { title: "Come giocare MALIANI in season 10 👨🏿 ► Age of Empires IV ◄ Gameplay ITA", id: "ZK5fPbCzeeI" },
  { title: "Season 10: nuova TIER LIST 1v1! 🔥 ► Age of Empires IV ◄ Gameplay ITA", id: "yrUsw7NcBiU" },
  { title: "Come fare fast imperial con MONGOLI 🐎 ► Age of Empires IV ◄ Gameplay ITA", id: "CSBO_dQhYy4" },
  { title: "Come fare fast castle con BURGRAVE con OOTD 🏹 ► Age of Empires IV ◄ Gameplay ITA", id: "zhSvMC6euco" },
  { title: "RHARESH vs VALDEMAR: esiste il rush dei lord di Lancaster?! 🤨 ► Age of Empires IV ◄ Gameplay ITA", id: "R5ZvaFmTobU" },
  { title: "3v3 su WATERLANES: ma è un team game o un triplo 1v1?! 🤔 ► Age of Empires IV ◄ Gameplay ITA", id: "Qs4G9XdCifU" },
  { title: "BEASTY vs VORTIX: chi avrà la meglio tra mongoli e Lancaster?", id: "stGrmOcwWBY" },
  { title: "La base dei LANCASTER brucia 🔥: come rushare con i TEMPLARI ► Age of Empires IV ◄ Gameplay ITA", id: "RONBa3ydUD0" },
  { title: "Devastazione totale in ladder giocando random civ: Bizantini e JD🌿► Age of Empires IV ◄ Gameplay ITA", id: "3TpCRZJGVi8" },
  { title: "[EN] RUS mirror: how to play the matchup 🏇🏽 ► Age of Empires IV ◄", id: "KVKLQROJv-A" },
  { title: "VORTIX vs NUMUDAN: come reagiscono i Delhi al tower rush? ♜ ► Age of Empires IV ◄ Gameplay ITA", id: "ox4pEuivqcM" },
  { title: "Rharesh affronta Anotand! 🥋 ► Age of Empires IV ◄ Gameplay ITA", id: "WYleGQJH6CI" },
  { title: "[EN] CAN I STOP ELAZER? I faced the SC2 pro everyone's talking about 😱 ► Age of Empires IV ◄", id: "TEpN6tA4UIs" },
  { title: "[EN] HOW TO REACH CONQUEROR FROM PLATINUM: the unstoppable samurai build 👹⚔☯⛩️ ► Age of Empires IV ◄", id: "HxlVI2JmSGI" },
  { title: "Analisi game livello diamante 💎 OOTD vs HRE ► Age of Empires IV ◄ Gameplay ITA", id: "50FBAal_5MY" },
  { title: "Guida ITA: all-in feudale con Cina e l'accademia imperiale ► Age of Empires IV ◄ Gameplay ITA", id: "13Vg4Um-gTM" },
  { title: "Guida ITA: come fare il Burgrave con pro scout dietro🦌 ► Age of Empires IV ◄ Gameplay ITA", id: "9tF33wSHaVc" },
  { title: "Analisi game livello platino🧊 HRE vs Ottomani ► Age of Empires IV ◄ Gameplay ITA", id: "xFRGNXAUe34" },
  { title: "OOTD contro Byz: miglior counter alla gulp build? 💦 ► Age of Empires IV ◄ Gameplay ITA", id: "5Z1prUa8Bqg" },
  { title: "Rharesh affronta la sua main civ 🐴 ► Age of Empires IV ◄ Gameplay ITA", id: "d_aIoM5Seq0" },
  { title: "Riuscirà Giovanna a fermare la civ del momento? 🐘 ► Age of Empires IV ◄ Gameplay ITA", id: "1tmWiCZBsnk" },
  { title: "TORNEO D.S. argento 🥰: Orsetti Gommosi vs Il Team che volevo ► Age of Empires IV ◄ Gameplay ITA", id: "-XZySJzlCGI" },
  { title: "Guida ITA: come fermare il nuovo meta Byz coi catafratti ♞ ► Age of Empires IV ◄ Gameplay ITA", id: "pAPlT9T5G7Y" },
  { title: "Analisi game livello oro 🥇 Delhi vs Abbasidi ► Age of Empires IV ◄ Gameplay ITA", id: "8-k8Gzx_f8w" },
  { title: "marcotamby vs gattoratto: quante vite ha il micio? 🐈 ► Age of Empires IV ◄ Gameplay ITA", id: "xWoBZ6RyPno" },
  { title: "TORNEO D. S. oro 🥰 Gli Appisolati vs Falena all'ascolana - GAME 3 ► Age of Empires IV ◄ Gameplay ITA", id: "jM_m5NE6i_U" },
  { title: "TORNEO D. S. oro 🥰 Gli Appisolati vs Falena all'ascolana - GAME 2 ► Age of Empires IV ◄ Gameplay ITA", id: "YvWXRqefuzg" },
  { title: "TORNEO D. S. oro 🥰 Gli Appisolati vs Falena all'ascolana - GAME 1 ► Age of Empires IV ◄ Gameplay ITA", id: "OEfl-z3xa-s" },
  { title: "TORNEO DELLA SIMPATIA oro🥰 King beduini di Ascoli vs GFC - GAME 2 ► Age of Empires IV ◄ Gameplay ITA", id: "heXzo1yuCe8" },
  { title: "Come battere Abbasidi con Delhi 👳: guida al feudal push perfetto ► Age of Empires IV ◄ Gameplay ITA", id: "vjM4rDqfocE" },
  { title: "TORNEO DELLA SIMPATIA oro🥰 King beduini di Ascoli vs GFC - GAME 1 ► Age of Empires IV ◄ Gameplay ITA", id: "1HjRzVgHbeY" },
  { title: "TORNEO DELLA SIMPATIA argento 🥰: Orsetti Gommosi vs PSP - GAME 3 ► Age of Empires IV ◄ Gameplay ITA", id: "uUXVnLtuyZ0" },
  { title: "TORNEO DELLA SIMPATIA argento 🥰: Orsetti Gommosi vs PSP - GAME 2 ► Age of Empires IV ◄ Gameplay ITA", id: "X5gQ-bR5hJ8" },
  { title: "TORNEO DELLA SIMPATIA argento 🥰: Orsetti Gommosi vs PSP - GAME 1 ► Age of Empires IV ◄ Gameplay ITA", id: "27DwsVH-i5c" },
  { title: "2v2 qualificazioni WTC marcotamby - C1PO vs Elyona - Core: GAME 2 ► Age of Empires IV ◄ Gameplay ITA", id: "gpTwsxzrOh0" },
  { title: "2v2 qualificazioni WTC marcotamby - C1PO vs Elyona - Core: GAME 1 ► Age of Empires IV ◄ Gameplay ITA", id: "t42rVBvOP9s" },
  { title: "Puppy vs Demu GAME 3: Cina contro Giovanna d'Arco 😵 ► Age of Empires IV ◄ Gameplay ITA", id: "1Xv7KzxSxV0" },
  { title: "Puppy vs Demu GAME 2: Zhu Xi's contro Ayyubidi 🤯 ► Age of Empires IV ◄ Gameplay ITA", id: "50-nZof-uGM" },
  { title: "Puppy vs Demu GAME 1: mercenari o elefanti? 😲 ► Age of Empires IV ◄ Gameplay ITA", id: "oc_3Z1VhdzA" },
  { title: "4v4 interno della Nazionale di Aoeitalia 🇮🇹 ► Age of Empires IV ◄ Gameplay ITA", id: "b0w3FsLZw-s" },
  { title: "Forse abbiamo esagerato con il buff agli elefanti 🥴 ► Age of Empires IV ◄ Gameplay ITA", id: "6ir0CKgj8M0" },
  { title: "Inglesi con strategia troll? ATTENZIONE! ► Age of Empires IV ◄ Gameplay ITA", id: "RJKPp9MmlKM" },
  { title: "Analisi game livello oro/platino 🥇 Bizantini vs Cinesi ► Age of Empires IV ◄ Gameplay ITA", id: "EhRODYQAWBU" },
  { title: "Analisi game livello oro 🥇 Francesi vs Maliani ► Age of Empires IV ◄ Gameplay ITA", id: "ke1j9wULVMw" },
  { title: "Analisi game livello oro 🥇 Ottomani vs HRE ► Age of Empires IV ◄ Gameplay ITA", id: "zRNJZ0tmqS8" },
  { title: "Season 9: analisi ITA patch notes, nerf e buff. IL CANTO DEL CIGNO DEL SIEGE? ► Age of Empires IV ◄", id: "bepUksv7AOk" },
  { title: "HRE vs Abba: quale S-Tier civ avrà la meglio? ► Age of Empires IV ◄ Gameplay ITA", id: "m2OxKag7XQ0" },
  { title: "Trade francese da CAPOGIRO: Rharesh sfoggia una COC pazzesca! 🍆 ► Age of Empires IV ◄ Gameplay ITA", id: "t-MJVp4Cza4" },
  { title: "TUTORIAL: come usare HOTKEYS, GRUPPI DI CONTROLLO E SHORTCUTS 🧐 ► Age of Empires IV ◄ Gameplay ITA", id: "bP9kbmEJxQ4" },
  { title: "MASS ARCHI CON DELHI 🏹: build order per team games ► Age of Empires IV ◄ Gameplay ITA", id: "5wsNUFVBc4s" },
  { title: "Delhi in imperiale: una delle civ più forti ► Age of Empires IV ◄ Gameplay ITA", id: "RdKnN8HWsUI" },
  { title: "Bizantini inarrestabili! ► Age of Empires IV ◄ Gameplay ITA", id: "O3EFMjs1EdM" },
  { title: "Analisi game livello oro 🥇 Inglesi vs OOTD ► Age of Empires IV ◄ Gameplay ITA", id: "Z6ARNxdZUqo" },
  { title: "Maliani: guida al cowboom e build order classico 🐄 ► Age of Empires IV ◄ Gameplay ITA", id: "4PTiDqbcreU" },
  { title: "Beasty vs LoueMT: Giapponesi vs Inglesi ♜ ► Age of Empires IV ◄ Gameplay ITA", id: "L-NnvO0EMSk" },
  { title: "Guida ITA: come fare tower rush con HRE ♜ ► Age of Empires IV ◄ Gameplay ITA", id: "m1UugMNb5dc" },
  { title: "Puppypaw vs Wam: Cina vs Zhu Xi's (Red Bull Wololo) ► Age of Empires IV ◄ Gameplay ITA", id: "C-slNNyLTak" },
  { title: "Puppypaw vs Wam: game di qualificazione Red Bull Wololo ► Age of Empires IV ◄ Gameplay ITA", id: "lhEdzA-O5Kg" },
  { title: "Season 8: la TIER LIST più calda dell'estate! 🔥 ► Age of Empires IV ◄ Gameplay ITA", id: "82LZDIG-y6k" },
  { title: "Guida ITA: linee guida per giocare HRE mirror 👓 ► Age of Empires IV ◄ Gameplay ITA", id: "_EiTWe2Gdzs" },
  { title: "Beasty contro Wam: game di qualificazione Red Bull Wololo ► Age of Empires IV ◄ Gameplay ITA", id: "de_bLsV6BJc" },
  { title: "2v2 con C1PO su Canal: Delhi OP su mappe ibride? ► Age of Empires IV ◄ Gameplay ITA", id: "X0glGHS-6NE" },
  { title: "Guida ITA: come fare il Bulgrave con HRE ► Age of Empires IV ◄", id: "QL_7XTGh68w" },
  { title: "Guida ITA: come giocare giapponesi su mappe d'acqua ► Age of Empires IV ◄ Gameplay ITA", id: "UoKNu2AjfsM" },
  { title: "Mongoli contro Ayyubidi: com'è cambiato il matchup post patch? ► Age of Empires IV ◄ Gameplay ITA", id: "F1DgoG4b2b4" },
  { title: "Ordine del Drago contro Delhi: è davvero un matchup impossibile? ► Age of Empires IV ◄ Gameplay ITA", id: "5mPqVHAkJ9U" },
  { title: "Analisi game livello oro 🥇 Rusiani vs Bizantini► Age of Empires IV ◄ Gameplay ITA", id: "bZPvZVuy800" },
  { title: "Rharesh contro Gorat: scontro totale su 4 laghi! Abbasidi vs HRE ► Age of Empires IV ◄ Gameplay ITA", id: "TrnGsB8njOg" },
  { title: "Maliani contro Mongoli: vincerà il trade o il cowboom? 🐄 ► Age of Empires IV ◄ Gameplay ITA", id: "mVj_dDf6Kds" },
  { title: "Guida ITA: come fermare il nuovo meta inglese con HRE 🐏 (+ Bulgrave!) ► Age of Empires IV ◄", id: "BRnRjOZEvh4" },
  { title: "Season 8: analisi ITA delle patch notes, nerf e buff vari. Inglesi ancora OP? ► Age of Empires IV ◄", id: "_3NLBsjCuDk" },
  { title: "Mongoli contro HRE: qualcuno ha detto picche in dark age?! ► Age of Empires IV ◄ Gameplay ITA", id: "SCl7x_2-juY" },
  { title: "Eredità di Zhu Xi's contro Maliani: Core prova a battere Beasty! ► Age of Empires IV ◄ Gameplay ITA", id: "kcblq47HGzU" },
  { title: "Guida ITA: come rushare con i francesi in feudale ► Age of Empires IV ◄ Gameplay ITA", id: "5UmUDsInRI0" },
  { title: "May contro Beasty: il ritorno dei Delhi?", id: "JMGJWXmB5JE" },
  { title: "Torneo Monociv Hero: Delhi (io) vs Inglesi (Chrysaor): analisi della sconfitta ► Age of Empires IV ◄", id: "qv-t8COdUIg" },
  { title: "Torneo Monociv Hero: Delhi (io) vs Abba (Gorat): analisi della sconfitta ► Age of Empires IV ◄", id: "AigSbuthKg4" },
  { title: "Mimmofalena contro 3D!CAT: il tower rush funzionerà? ► Age of Empires IV ◄ Gameplay ITA", id: "3kRkJcyP5WI" },
  { title: "4 laghi: quale civ performa meglio su questa mappa? 🐟 ► Age of Empires IV ◄ Gameplay ITA", id: "LMHDa4Z0QNY" },
  { title: "Guida ITA: Come fare tower rush con il Sacro Romano Impero (stream 💻) ► Age of Empires IV ◄", id: "oSCSyoDkLM4" },
  { title: "Fare all in con la Dinastia Abbaside? Ala militare + 1 TC build 👀 ► Age of Empires IV ◄ Gameplay ITA", id: "N7C-EHk-Up8" },
  { title: "Beasty vs Lucifron su Arcipelago: il game più assurdo di sempre su acqua! ► Age of Empires IV ◄", id: "XVZz2RGxDNg" },
  { title: "Gioco contro un pro player: cosa potrebbe andare storto? 🙈 ► Age of Empires IV ◄ Gameplay ITA", id: "sD8GS0fydCA" },
  { title: "KING OF THE HILL: 5 secondi alla vittoria sacra! 😱😱😱 ► Age of Empires IV ◄ Gameplay ITA", id: "W7Ms4yEn2Bc" },
  { title: "Guida ITA: Come fare fast castle con il Sacro Romano Impero ► Age of Empires IV ◄ Gameplay ITA", id: "yxws2qQBvqE" },
  { title: "Guida ITA: Come fermare la fast castle giapponese coi Bizantini ► Age of Empires IV ◄ Gameplay ITA", id: "WuO27sFFziM" },
  { title: "Tower rush sulle bacche di Delhi? No problem! ► Age of Empires IV ◄ Gameplay ITA", id: "qf1mUdIn4i4" },
  { title: "Man at arms francesi: nuovo meta? ► Age of Empires IV ◄ Gameplay ITA", id: "tnIr4DNaOZo" },
  { title: "EN guide: Ayyubids game analysis in AoEIV ► Age of Empires IV ◄", id: "cacvDac1U0o" },
  { title: "Guida ITA: AGGRESSIONE FEUDALE DELL'ORDINE DEL DRAGO ► Age of Empires IV ◄", id: "jt-ZAaejaQs" },
  { title: "GIOVANNA D'ARCO È ROTTISSIMA! Guida ITA alla nuova variante dei Francesi ► Age of Empires IV ◄", id: "dQQ3IASE0nU" },
  { title: "Guida ITA al Sultanato di Delhi: BUILD ORDER PER RUSH FEUDALE ► Age of Empires IV ◄", id: "eT8Px9TSZO4" },
  { title: "Guida ITA agli inglesi: RUSH FEUDALE SUPER AGGRESSIVO ► Age of Empires IV ◄", id: "Js0YZ-BZIRY" }
];
